### ISSUE TITLE
Where are the hard coded nodes?

### ISSUE THREAD

**Issue by taismi** [HOdlcoin/HOdlcoin#103]
This list seems to list only Bitcoin nodes.
https://github.com/HOdlcoin/HOdlcoin/blob/HODLCoin0.11.3/contrib/seeds/nodes_main.txt

**Comment by ghobson2013** [comment]
Hi there, 
The seednodes are stored in src/chainparams.cpp
example of on in that list is "eastcoast.hodlcoin.com" 

Regards,
//ghobson
