### ISSUE TITLE
Windows wallet doesn't find nodes

### ISSUE THREAD

**Issue by taismi** [HOdlcoin/HOdlcoin#105]
I was installing Hodlcoin wallet to my friend. Installation was ok. Wallet connected to two nodes 96.44.157.195 and 54.213.21.170. Both are hard coded nodes in src/chainparams.cpp. Wallet does not find any other nodes?

Shouldn't those hard coded nodes send other nodes to my wallet node?

Looks like all nodes need to be connected together manually. Is the distributed network failing? Those hard coded nodes are quite slow and my wallet reconnects quite often.

debug.log says
`2017-10-02 14:07:51 P2P peers available.`
but only those hard coded nodes are connected.

_2017-10-02 14:07:40 mapWallet.size() = 0
2017-10-02 14:07:40 mapAddressBook.size() = 1
2017-10-02 14:07:40 init message: Loading addresses...
2017-10-02 14:07:40 Loaded 7 addresses from peers.dat  0ms
2017-10-02 14:07:40 dnsseed thread start
2017-10-02 14:07:40 init message: Done loading
2017-10-02 14:07:40 net thread start
2017-10-02 14:07:40 opencon thread start
2017-10-02 14:07:40 addcon thread start
2017-10-02 14:07:40 msghand thread start
2017-10-02 14:07:40 GUI: PaymentServer::LoadRootCAs: Loaded  93  root certificates
2017-10-02 14:07:41 sort hodlings flag = 1
2017-10-02 14:07:41 sort hodlings flag = 1
2017-10-02 14:07:41 sort hodlings flag = 1
2017-10-02 14:07:47 receive version message: /HOdlcoin:3.0.1/: version 250000, blocks=324929, us=xxx.xxx.xxx.xxx:1163, peer=1
2017-10-02 14:07:47 Added time data, samples 2, offset -9 (+0 minutes)
2017-10-02 14:07:48 receive version message: /HOdlcoin:3.0.0/: version 250000, blocks=324929, us=xxx.xxx.xxx.xxx:1164, peer=2
2017-10-02 14:07:48 Added time data, samples 3, offset -1 (+0 minutes)
2017-10-02 14:07:51 P2P peers available. Skipped DNS seeding.
2017-10-02 14:07:51 dnsseed thread exit_

There is a line
`2017-10-02 14:07:40 Loaded 7 addresses from peers.dat 0ms`
Those 7 addresses are all hard coded addresses. Only two are working.

Windows 10 pro 64 bit. I have not tested if Linux version has problems.

**Comment by taismi** [comment]
If I set debug=net I get
_2017-10-02 15:52:33 received: addr (30003 bytes) peer=1
2017-10-02 15:52:55 received: addr (30003 bytes) peer=2_
but wallet node is not connecting.

**Comment by taismi** [comment]
64 bit Linux version found 8 nodes.

**Comment by AmiT177** [comment]
Go to %appdata%, HOdlcoin, and create a file named hodlcoin.conf.
paste this in, and then launch the wallet:

`
addnode=2a01:4f8:10a:657::2
addnode=88.99.30.25
addnode=204.65.73.88
addnode=2a07:bbc0:0:1001:2e4d:54ff:fef0:20e9
addnode=4.28.11.195
addnode=71.89.135.178
addnode=104.233.80.15
addnode=88.217.187.63
addnode=93.191.123.67
addnode=87.237.26.28
addnode=107.132.209.99
addnode=54.213.21.170
addnode=41.177.143.235
addnode=217.147.160.30
addnode=37.120.189.15
addnode=2a01:4f8:212:d86::2
addnode=195.154.58.251
addnode=192.186.73.3
addnode=86.88.34.22
addnode=51.15.162.15
addnode=62.218.117.98
addnode=137.189.91.64
addnode=88.99.25.20
addnode=136.243.45.140
addnode=2a01:4f8:120:90d0::2
addnode=78.46.99.10
addnode=144.76.40.144
addnode=37.187.27.4
addnode=1.124.111.158
addnode=83.216.106.95
addnode=185.160.90.73
addnode=59.167.239.127
addnode=87.149.96.7
addnode=37.221.204.26
addnode=84.193.219.191
addnode=97.88.9.66
addnode=96.234.50.181
addnode=88.135.238.20
addnode=73.48.20.121
addnode=130.194.84.212
addnode=85.131.28.119
addnode=66.90.175.20
addnode=68.142.150.4
addnode=176.221.11.6
addnode=98.150.214.246
addnode=176.221.11.6
addnode=62.33.168.46
addnode=212.17.241.225
addnode=178.82.243.129
addnode=88.152.186.138
addnode=162.213.184.133
addnode=216.21.163.205
addnode=74.133.96.215
addnode=173.212.225.176
addnode=81.166.88.45
addnode=81.10.184.122
addnode=62.159.95.187
addnode=81.174.233.1
addnode=69.167.204.2
addnode=217.147.160.71
addnode=2601:2c4:c580:3840:b052:f9f4:bfb:e10e
addnode=31.162.230.30
addnode=83.216.106.95
addnode=79.120.218.151
addnode=71.82.185.164
addnode=82.44.92.21
addnode=86.12.187.141
addnode=69.196.67.109
addnode=82.152.182.147
addnode=24.176.136.63
addnode=193.104.177.30
addnode=91.190.8.229
addnode=71.14.25.114
addnode=24.9.242.116
addnode=113.161.82.243
addnode=45.35.54.7
addnode=99.1.174.9
addnode=73.229.231.29
addnode=43.240.102.66
addnode=149.140.80.149
addnode=212.112.149.17
addnode=94.210.142.253
addnode=196.52.39.5
addnode=195.137.178.130
addnode=110.175.118.222
addnode=206.221.178.51
addnode=185.75.148.2
addnode=120.197.181.171
addnode=98.109.217.20
addnode=91.112.41.147
addnode=181.53.45.38
addnode=178.189.184.107
addnode=94.253.12.82
addnode=114.77.113.206
addnode=213.108.119.84
addnode=83.135.125.3
addnode=47.186.73.131
addnode=176.97.36.65
addnode=79.217.237.117
addnode=91.44.196.24
addnode=69.254.63.56
addnode=94.253.12.82
addnode=132.147.78.235
addnode=49.65.128.51
addnode=108.27.57.244
addnode=176.117.234.28
addnode=94.25.170.156
addnode=91.185.33.20
addnode=83.239.106.110
addnode=94.78.99.123
addnode=112.207.10.245
addnode=124.65.131.74
addnode=95.88.174.187
addnode=172.116.254.246
addnode=120.197.181.171
addnode=109.93.224.90
addnode=49.148.157.112
addnode=109.172.13.153
addnode=188.71.255.75
addnode=91.118.74.68
addnode=69.254.63.56
addnode=79.179.6.137
addnode=136.243.174.195
addnode=91.112.41.147

`
