### ISSUE TITLE
Wallet crashing with more than one BerkeleyDB

### ISSUE THREAD

**Issue by AmiT177** [HOdlcoin/HOdlcoin#112]
### System
**Operation System:** Ubuntu 16.04
**Wallet Version:** v3.0.0.99-0a6f795
**Linux GCC Version:** gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

----

### Description of issue
Wallet crashing if you have more than one BerkeleyDB version installed
and you use `./configure --with-incompatible-bdb`

----

### Steps to reproduce
1. Install more than one version of BerkeleyDB.
2. Install the wallet, and after `./autogen.sh`, use `./configure --with-incompatible-bdb`.
3. Launch the wallet.
----

### Logs
If exists, attach the debug.log file. (/.hodlcoin/debug.log)
[debug.log](https://github.com/HOdlcoin/HOdlcoin/files/1651656/debug.log)

**Comment by ghobson2013** [comment]
in my experience compiling with "--with-incompatible-bdb" doesn't work.
The codebase currently only support libdb4.8.30 , this is the reason the pre-requirements is downloading and compiling from source db-4.8.30.NC.tar.gz

**Comment by AmiT177** [comment]
yeah well, the problem is that if you have more than 1 version of BDB, for example, a newer one, it would tell you to either delete it or use `--with-incompatible-bdb`.  and if you use `--with-incompatible-bdb` the wallet would "crash" when you run it.

Could we remove the option to use `--with-incompatible-bdb` and change it to an error that tells you  that you have to remove the other versions?

**Comment by ghobson2013** [comment]
it shouldn't happen if they follow build instructions described here https://github.com/HOdlcoin/HOdlcoin/blob/HODLCoin0.11.3/doc/build-unix.md  , perhaps this is the document that should be adjusted and made easier to understand.

**Comment by AmiT177** [comment]
Removed the "is not recommended" part. because it just breaks the wallet.
Anyway, I still think we need to edit it so you won't be able to compile it if you have more than one version.
Would save time for other people trying to figure out what was wrong in their installation.

**Comment by ghobson2013** [comment]
your welcome to cleanup the instructions, i also have build instructions for centos7 and fedora27
