### ISSUE TITLE
Replugging HDMI cable causes segfault after clicking menu item.

### ISSUE THREAD

**Issue by Qwertylex** [HOdlcoin/HOdlcoin#116]
### System

**Operation System:** (Archlinux)
**Wallet Version:** (3.0.1)
**Linux GCC Version:** (7.2.1 20180116)
XFCE4, Linux 4.14.15-1-ARCH, i915 driver

----

### Description of issue
Segmentation fault on a Sandy Bridge Intel Pentium G630 2.7 GHz with Intel HD 2000 Graphics

----

### Steps to reproduce
1. Click on "Mining" tab.
2. Unplug HDMI cable from back of PC
3. Plug HDMI cable back in.
4. Click on "Mining" tab.

----

### Logs
If exists, attach the debug.log file. (/.hodlcoin/debug.log)

[segfault.txt](https://github.com/HOdlcoin/HOdlcoin/files/1679463/segfault.txt)

**Comment by Qwertylex** [comment]
I'm thinking its probably an issue with xfdesktop and intel gpu drivers rather than hodlcoin.
Maybe something like this happened; xfdesktop sefgaulted because of something not handled properly with HDMI replug/intel drivers, and hodlcoin crashed because of something it couldn't properly communicate to xfdesktop about after its crash or something like that.
**(Which seems odd from a laymans perspective because there were no visible signs of  corruption after the HDMI replug, everything acted normally, all other programs acted normally, hodlcoin is the only program that visibly failed, and this issue is specific to the Mining tab for some reason.)**
I'm going to follow https://01.org/linuxgraphics/documentation/how-report-bugs
and https://bugzilla.xfce.org/enter_bug.cgi?product=Xfdesktop
and I'll post bug reports on both of them later, referencing this post. That should help.

**Comment by ghobson2013** [comment]
closing this , since its not hodlcoin's fault.
