### ISSUE TITLE
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

### ISSUE THREAD

**Issue by pinney** [HOdlcoin/HOdlcoin#123]
### System
x86_64
Intel(R) Core(TM) i3-4130T CPU @ 2.90GHz
**Operation System:** (Windows 10/Ubuntu 16.04 etc)
cat /etc/debian_version
9.3
**Wallet Version:** (help --> debug/hodlcoind --version)
git branch
  3.0
* 3.0.2
  HODLCoin0.11.3

**Linux GCC Version:** (none on windows/gcc --version)
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
----

### Description of issue
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!
----

### Steps to reproduce
1. git clone 
2. git checkout 3.0.2
3. ./autogen.sh
4. ./configure
5. optionally  ./configure --with-libressl
6. make

----

### Build Log

IF ./configure --with-libressl is used.
make fails with ;

Making all in src
make[1]: Entering directory '/xxx/HOdlcoin/src'
make[2]: Entering directory '/xxx/HOdlcoin/src'
  CXX      libbitcoinconsensus_la-ecwrapper.lo
ecwrapper.cpp: In function ‘int {anonymous}::ECDSA_SIG_recover_key_GFp(EC_KEY*, ECDSA_SIG*, const unsigned char*, int, int, int)’:
ecwrapper.cpp:73:28: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_add(x, x, ecsig->r)) { ret=-1; goto err; }
                            ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp:94:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_inverse(rr, ecsig->r, order, ctx)) { ret=-1; goto err; }
                                  ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp:96:31: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_mul(sor, ecsig->s, rr, order, ctx)) { ret=-1; goto err; }
                               ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp: In member function ‘bool CECKey::Recover(const uint256&, const unsigned char*, int)’:
ecwrapper.cpp:180:32: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&p64[0],  32, sig->r);
                                ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp:181:32: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&p64[32], 32, sig->s);
                                ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
Makefile:5689: recipe for target 'libbitcoinconsensus_la-ecwrapper.lo' failed
make[2]: *** [libbitcoinconsensus_la-ecwrapper.lo] Error 1
make[2]: Leaving directory '/xxx/HOdlcoin/src'
Makefile:6637: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/xxx/HOdlcoin/src'
Makefile:643: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ghobson2013** [comment]
So your trying to build the wallet for Debian 9.3
We do not support libressl or openssl1.1.x right now.

if you need to compile from source, you need to first build the dependencies, 
cd depends and then type make
Once you have built the dependencies you then need to go back to the root directory and type 
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-unknown-linux-gnu --enable-tests=no
make 

This way the build process uses the dependencies compiled from source instead of the libraries in your OS.

**Comment by pinney** [comment]
Thanks for the timely response Gary : 
Unfortunately using ./configure --prefix=$pwd/depends/x86_64-unknown-linux-gnu --enable-tests=no
Ends with same error.
Maybe it's not using the dependencies from /depends ?

**Comment by ghobson2013** [comment]
did you first do
cd depends
make
?

**Comment by pinney** [comment]
Yes ... now depends has the x86_64-unknown-linux-gnu directory.

**Comment by ghobson2013** [comment]
I setup a new VM with Debian streatch 9.4 , and using my instructions was able to build without the errors you have, i did the following:

apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev
apt-get install libqt4-dev libprotobuf-dev protobuf-compiler
ps: not sure libqt4-dev is needed
cd depends
make -j2
cd ..
./autogen.sh
./configure --prefix=/home/builder/hodlcoin/depends/x86_64-unknown-linux-gnu --enable-tests=no
make -j2
and now i got the binaries for 3.0.2

if you want i can upload them to the release page ?

**Comment by ghobson2013** [comment]
i released it just in case someone wants it, https://github.com/HOdlcoin/HOdlcoin/releases/download/v3.0.2/hodlcoin-3.0.2-x86_64-debian94.tgz

**Comment by pinney** [comment]
I just ran though it again ... confirmed working!!

Maybe should make a note in the doc/build.unix.md to use the dependencies found in /depends?

./configure --prefix=/PATH/TO/HOdlcoin/depends/x86_64-unknown-linux-gnu --enable-tests=no

Thanks!!!
