### ISSUE TITLE
3.0.2 on OSX - states "pre-release test build"

### ISSUE THREAD

**Issue by yzhodl** [HOdlcoin/HOdlcoin#124]
When I start the program, it says "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications".

Should I use 3.0.1 for mining?

**Comment by ghobson2013** [comment]
its ok, you can mine safely. 
so when you start https://github.com/HOdlcoin/HOdlcoin/releases/download/v3.0.2/hodlcoin-3.0.2-osx-unsigned.dmg  you get that warning ?

**Comment by yzhodl** [comment]
Yes, that is correct. The warning is displayed as a banner in the HOdlcoin
Core - Wallet.

In addition, how do I run it using command-line for the iMac and provide
these options?
-optimineraes=1
-optimineravx2=1

**Comment by ghobson2013** [comment]
ok i will fix the banner and make a new osx dmg file.

To pass arguments to hodlcoin , you need to make a hodlcoin.conf file in the same folder as the debug.log and wallet.dat file default location  is in the application support folder/Hodlcoin
Inside the conf file you can then add optimineraes=1 and optimineravx2=1

**Comment by yzhodl** [comment]
Ok. Thank you for the prompt response.

I made hodlcoin.conf in the same folder as debug.log and added the options. 

This is the first time running on iMac with HighSierra OS. Once it syncs with the network, I'll enable mining.

**Comment by ghobson2013** [comment]
thanks for bring it to my attention, 
I have recreated the correct dmg file , it was a compiler flag issue.
https://github.com/HOdlcoin/HOdlcoin/releases/download/v3.0.2/hodlcoin-3.0.2-osx-unsigned.dmg

**Comment by yzhodl** [comment]
You are welcome, and thank you for the fix.
