### ISSUE TITLE
3.0.2 Threads - OSX vs Windows

### ISSUE THREAD

**Issue by yzhodl** [HOdlcoin/HOdlcoin#125]
3.0.2 on Windows with i7 shows 1 Miner, 8 Threads when I hover over the mining axe.
3.0.2 on iMac with i5 shows 1 Miner, 4 Threads when I hover over the mining axe.

Is there a way to increase the number of threads for iMac? I tried adding the following to holdcoin.conf - but that didn't work.
rpcthreads=8

**Comment by ghobson2013** [comment]
rpcthreads is related to RPC cli commands not mining.
Orava's FAQ answers what you want to know, here is an extract:

THREAD COUNT AND MINER MEMORY:
By default Hodlcoin wallet uses 1 GB memory and sets thread count to match your CPU's cores but you can define memory usage and thread count by manually.
Parameter 'minermemory' defines memory for mining as giga bytes (1, 2, 3 etc). For example using 2 GB memory is equivalent for running 2 miners in parallel.
Parameter 'genproclimit' defines how many threads are used on each GB (this number must be a power of 2 so 2,4,8,16, etc).
You can add parameters 'minermemory' and 'genproclimit' to your hodlcoin.conf 

For example 
	minermemory=2
	genproclimit=4
in your hodlcoin.conf
sets wallet miner to use 2 GB of memory with 4 threads on each GB, total 8 threads.

**Comment by yzhodl** [comment]
Thank you. Can you please provide the url to Orava's FAQ.

**Comment by yzhodl** [comment]
I added the following to hodlcoin.conf
genproclimit=8
minermemory=1

I still get Miners:1, Threads:4 on the OSX with 3.0.2

**Comment by ghobson2013** [comment]
http://hodlwallet.amit.systems:1779/
