### ISSUE TITLE
Fee calculation issue/clarification request

### ISSUE THREAD

**Issue by ghobson2013** [HOdlcoin/HOdlcoin#126]
### System

Happens on all OS's

----

### Description of issue

As far as I can tell the problem is the accumulated interest an input earns every block is being used as a fee when sending coins. The code usually selects coin control entries automatically, so depending on when it was the last time you used that coin control entry the fee will be higher ( since older age means more interest earned ). This means the fee will never be more than the earned interest of a single coin control input entry.

CreateTransaction() in wallet.cpp seems to be the source of the problem, 
gettransaction says the Fee is equal to GetValueOut() - GetDebit().
But GetDebit() does not take into account per block earned interest for the coinage, so the final Fee is off by a large amount ( up to the entire earned interest for that coin control entry ).

----

### Steps to reproduce
Use coin control and select an input with high interest, 
send 100 coins from it, and you will see a high fee for it, resembling the entire accumulated interest of those inputs.

Example:
http://cdn.amit.systems/2018-04-03_17-52-42.png
The following 2 inputs were send to another single address ( total of 100 coins ).
tx fee should be 0.00001870 HODL
the fee reported by gettransaction() rpc call is 0.40412280 HODL

----

I am not sure how to resolve this, but this cannot be the intend of the creator ;)

**Comment by FreeTrade** [comment]
So I suspect the error is in the gettransaction() rpc call

Still an issue, but a minor one by comparison.

**Comment by ghobson2013** [comment]
This happens with the wallet but only when someone is sending coins to someone else and the chosen coin control entry has earned more than 0.1 HODL interest ( lower and you wont notice it )...  The fee then becomes equal to the earned interest minus the relay fee.   It cannot be the intention of the code to consume the earned interest as a sending fee ?

**Comment by ghobson2013** [comment]
I was wondering why GetDebit() call doesnt take into account earned interest ? ( like GetCredit() does ) , Since the Fee ends up calculated as GetValueOut() - GetDebit() , surely both calls need to take into account the per block interest earned ? ( otherwise it simply becomes the fee )

**Comment by FreeTrade** [comment]
For a transaction, we only need to compute interest on the inputs - the outputs won't have accumulated any interest yet.

**Comment by ghobson2013** [comment]
verified and tested FreeTrade's submitted fix in development branch.
