### ISSUE TITLE
Sign Message doesnt work with encrypted wallets

### ISSUE THREAD

**Issue by PWRcoin** [HOdlcoin/HOdlcoin#127]
### System

**Operation System:** (Windows 10/Ubuntu 16.04 etc)
All OS's
**Wallet Version:** (help --> debug/hodlcoind --version)
v3.0.2
**Linux GCC Version:** (none on windows/gcc --version)

----

### Description of issue

Once you encrypt your wallet, sign message returns address not recognized error , no matter
which receive key you use.
The underlying RPC calls are working properly, it is the GUI that is not able to accept the HODL
address.
 
----

### Steps to reproduce
1. encrypt wallet
2. sign message

----

### Logs
If exists, attach the debug.log file. (/.hodlcoin/debug.log)
debug logs do not container anything, the GUI shows address not recognized.

**Comment by ghobson2013** [comment]
I will look into it.

**Comment by ghobson2013** [comment]
closing this issue since it was fixed, will be included in v3.0.3
