### ISSUE TITLE
Logo source file?

### ISSUE THREAD

**Issue by sindresorhus** [HOdlcoin/HOdlcoin#130]
Where can I find the source file (not `png`) of the project logo?

I would like to submit it to https://github.com/cjdowner/cryptocurrency-icons

**Comment by AmiT177** [comment]
SVG: http://hodlcoin.com/img/logo.svg

**Comment by sindresorhus** [comment]
Thank you! Submitted: https://github.com/cjdowner/cryptocurrency-icons/issues/112

I would recommend creating a page on the website to find project related media assets.

**Comment by AmiT177** [comment]
Good to know!

**Comment by sindresorhus** [comment]
https://github.com/lukechilds/hyperdex/releases/tag/v0.1.0-alpha.1

**Comment by AmiT177** [comment]
Thanks!

**Comment by AmiT177** [comment]
It doesn't look like hodlcoin is there

**Comment by AmiT177** [comment]
I enabled HOdlcoin on my currency list, but when I click deposit, there is a wrong address generated.
