### ISSUE TITLE
epends

### ISSUE THREAD

**Issue by danrachita** [HOdlcoin/HOdlcoin#135]
### System

**Operation System:** (Windows 10/Ubuntu 16.04 etc)
**Wallet Version:** (help --> debug/hodlcoind --version)
**Linux GCC Version:** (none on windows/gcc --version)

----

### Description of issue

----

### Steps to reproduce
1.
2.
3.

----

### Logs
If exists, attach the debug.log file. (/.hodlcoin/debug.log)

**Comment by AmiT177** [comment]
Invalid issue, none of the items were filled.
Closed
