### ISSUE TITLE
Change Alert Key

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#16]

**Comment by Fuzzbawls** [comment]
Best practice principles here would be to change this in current source ASAP so it can be distributed amongst the network. Then, when it comes time to actually send an alert, the receiving ratio is much higher.

I can make this change, but in doing so I would hold the privkey for the alert system. I'm ok with that, but if anyone else needed it I have my own security standards in how to transmit said privkey that would need to be followed.

**Comment by FreeTrade** [comment]
I'll create an alert key. I did it before on Memorycoin so am familiar with the process. Was just a bit busy with other stuff this launch. :)
