### ISSUE TITLE
Update version number to not follow BTC

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#17]

**Comment by Fuzzbawls** [comment]
I think it may be better to adopt a unique versioning scheme rather than to just tack on to the BTC fork version.

Not difficult to do, just need consensus

**Comment by FreeTrade** [comment]
Yes changing the versioning scheme is fine by me, any thoughts on what to move to?

**Comment by Fuzzbawls** [comment]
one idea for versioning standards:

CLIENT_VERSION_MAJOR: start at 1. Only update for protocol or sweeping changes (hardforks etc)
CLIENT_VERSION_MINOR: start at 0. Update for new feature sets (layout changes/additions)
CLIENT_VERSION_REVISION: start at 0. Update for in-set fixes/patches 
CLIENT_VERSION_BUILD: 0 for release builds; 99 for test builds

**Comment by Vetro7** [comment]
Looks good to me

**Comment by Fuzzbawls** [comment]
Resolved in #36
