### ISSUE TITLE
Make HOdlings table sortable

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#18]

**Comment by Fuzzbawls** [comment]
This will be non-op and pushed back to a future point release for the time being.

**Comment by GENiALi** [comment]
+1

**Comment by michelem09** [comment]
+1

**Comment by ghobson2013** [comment]
submitted fix for this issue, 
pull request has been merged.
https://github.com/HOdlcoin/HOdlcoin/pull/87

**Comment by FreeTrade** [comment]
Alphabetic sort added. Not ideal, but big improvement.
