### ISSUE TITLE
If insufficient balance to hodl, deposit fails silently

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#26]
Should alert user to insufficient funds

**Comment by Fuzzbawls** [comment]
Somewhat addressed in #49 with coin control enabled. Using coin control will show dynamic "Insufficient Balance" text if the selected blocks aren't enough to cover the deposit amount. 

Without Coin Control enabled however, the silent fail remains.

**Comment by FreeTrade** [comment]
Sort of baffled - the EMIT message command was not bringing up a message box even though the code is identical to the send coins code. Anyway, replaced it with a message box and seems to fix it.
