### ISSUE TITLE
Separate Immature Balance

### ISSUE THREAD

**Issue by Fuzzbawls** [HOdlcoin/HOdlcoin#28]
Proposal to separate the Immature balance readout into two different labels as a convenience change.

- Immature (mined)
- Immature (HOdled)

**Comment by FreeTrade** [comment]
Agree, we should do this.

**Comment by Fuzzbawls** [comment]
Been testing a solution for this, but it still needs refinement when using watch-only addresses

**Comment by Fuzzbawls** [comment]
Closing this as it is now a moot point with the post-fork requirements.
