### ISSUE TITLE
Totals column on HOdlings table

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#29]
would be nice.

**Comment by michelem09** [comment]
+1

**Comment by ghobson2013** [comment]
i will look into this.

**Comment by ghobson2013** [comment]
need more guidance on this one, there is already a total immature value field on the UI, what additional info do we want to see ?

**Comment by michelem09** [comment]
I think we are talking about totals for each column on a fixed (bottom) row on the overview table

**Comment by ghobson2013** [comment]
ok so something like this ?
http://oi65.tinypic.com/2w1zb15.jpg

I have not found a way to freeze the row, sorting will mess it up.

**Comment by michelem09** [comment]
Cool, may be you can render it after the latest item row and after sort? So it should render always there

**Comment by ghobson2013** [comment]
Instead of messing with layouts and spacing , i am going to add total Principal / total Interest Accrued and total Value Accrued as Labels between Pending and Immature values in the top left.
I will post a screen shot when i have a working version, and then we can device if this is a good candidate for a pull request.

**Comment by ghobson2013** [comment]
alright here is my first proposal, 
http://i.imgur.com/K9yXG0n.jpg

FreeTrade this should also handle the other issue that was asking for a way to see if any hodlings had matured.

Locked: means total coins invested / locked in hodlings
Accrued: means interest earned on it so far.
Matured: means total balance of hodlings that have matured and therefor no longer earning interest.

I need to do more testing, but right now i am struggling trying to get testnet to sync with my test wallet.

**Comment by FreeTrade** [comment]
I think peeps are going to be confused what all the different terms are and why they don't add up to the total
I'm a bit confused myself.
This feature request was for a totals column on the HOdlings table. That should probably have been a row, not a column. It could be legend if a row is tricky to do in a dynamic table.

**Comment by ghobson2013** [comment]
i had a prototype working with a totals row but it gets lost when using any column sorting.
qt4 doesnt support freezing a row out of the box. 
I tried adding a second table but then the challenge becomes matching row width with table 1.

As for the names well we could at least keep "Matured:", that is essentualy a good warning about having coins that are not earning interest ?

**Comment by FreeTrade** [comment]
Hmmm, Matured should probably be moved out of there too. I think we a clear idea of what information we're trying to convey. The different categories are kind of complex. I think i'll need to make a venn diagram of them to get them clear in my own mind

**Comment by FreeTrade** [comment]
Ok, I think these are all the figures people might be interested in at a glance -

Two main categories

I. Available
 a)Earning Interest
  1. Received Amounts			X
  2. Accrued Interest on 1.		        X
 
 b)Not Earning Interest
  1. Received Amounts			X		
  2. Interest Earned on 1.		        X
  3. Matured HODLings			X
  4. Interest Earned on 3.		        X
					          ------
  Total Available                            XXX

II. HODL'd
  a) HODL'd amounts (including mined, pending) X
  b) Accrued interest on a)                                    X
					                             --------
  Total HODL'd                                                  XXX

Overall Total                                   XXXX

**Comment by ghobson2013** [comment]
I can see how that becomes information overload ;)
I will restore the balance info the way it was and put the totals below the hodlings table
as labels, see how that comes out.. i ll publish a screenshot when i got it running.

**Comment by ghobson2013** [comment]
ok here is my second proposal..
http://imgur.com/pgH2exS

**Comment by FreeTrade** [comment]
Yup, looks good - clear information. 

Maybe have all three on the same row so it takes up less vertical space.

Maybe also change the name of 'Immature' to 'HOdl'd'

**Comment by ghobson2013** [comment]
Like this ? 
http://imgur.com/a/jinl1

**Comment by FreeTrade** [comment]
Looks good!

**Comment by ghobson2013** [comment]
ok i ll will submit a pull request for it. i also upped the CLIENT_REVISION_VERSION to 1 , since 3.0.1

**Comment by ghobson2013** [comment]
https://github.com/HOdlcoin/HOdlcoin/pull/100

**Comment by ghobson2013** [comment]
only did basic testing, it looked ok to me, but this probably needs more eyeballs, just to see the math is correct.
