### ISSUE TITLE
Splash screen crash  

### ISSUE THREAD

**Issue by Vetro7** [HOdlcoin/HOdlcoin#32]
"the splash comes up, and it appears to load normally...then the program kills itself & disappears"
Found by BTT user Arrakeen
https://bitcointalk.org/index.php?topic=1317918.msg13945770#msg13945770

**Comment by Fuzzbawls** [comment]
Issue is a placeholder and borderline invalid without further details/information.

Marking as such for now.

**Comment by Vetro7** [comment]
Yep I will be posting in BTT for further info

**Comment by Fuzzbawls** [comment]
2 weeks without any further information.

Closing and marking as invalid.
