### ISSUE TITLE
"Out of Memory" error message

### ISSUE THREAD

**Issue by Vetro7** [HOdlcoin/HOdlcoin#33]
![download](https://cloud.githubusercontent.com/assets/8535388/13199500/095f6604-d7f5-11e5-936e-9f009d5af40a.png)

Found by BTT user antonio8
https://bitcointalk.org/index.php?topic=1317918.msg13944650#msg13944650

**Comment by Fuzzbawls** [comment]
Likely a host and/or user issue. Over utilization of system resources isn't what the wallet is doing on Linux or Mac, and no other reports from Windows users.

**Comment by Vetro7** [comment]
Yes this was my first thoughts, the user stated 16gb of system memory also using default mining settings.  However this doesn't mean that he isn't still over utilizing.

**Comment by Fuzzbawls** [comment]
All of my Linux based instances are using just over 4gb RAM (-minermemory=4) and have been running for quite a while now.

Unless we see solid documented evidence of a Windows-specific memory leak, I'm inclined to close this and chalk it up to User error.

**Comment by Vetro7** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8535388/13200615/9e8fb480-d81e-11e5-942d-d90465d89a2c.png)

This is a 8 core 24gb Windows 8.1 System
The wallet has  been running for 6 days with settings -minermemory=2 -genproclimit=4

**Comment by Vetro7** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/8535388/13200696/791b29b6-d821-11e5-997a-4f2d128ec717.png)

Windows 2012 R2 - 64-bit (Standard) 16 vCore RAM:64 GB
he wallet has been running for 8 days with settings -minermemory=2 -genproclimit=8

**Comment by Fuzzbawls** [comment]
2 weeks without any further information.

Closing and marking as invalid.
