### ISSUE TITLE
Deposit tab needs balance info

### ISSUE THREAD

**Issue by Vetro7** [HOdlcoin/HOdlcoin#34]
The Deposit tab should have the available balance in lower right like the Send tab has.

**Comment by Vetro7** [comment]
We should also consider added Coin Control to the Deposit tab

**Comment by Fuzzbawls** [comment]
yeah coin control for deposits is needed

**Comment by FreeTrade** [comment]
I think deposits may already use coin control selections from the send tab. Needs testing and clearer explanation of what's going on + button to bring up coin control from deposits.
