### ISSUE TITLE
ARM based builds not supported

### ISSUE THREAD

**Issue by Fuzzbawls** [HOdlcoin/HOdlcoin#41]
Compiling on ARM architectures is currently not supported. Error as follows:

`patternsearch.cpp: In function ‘void patternsearch::cpuid(unsigned int, unsigned int*, unsigned int*, unsigned int*, unsigned int*)’:
patternsearch.cpp:263:21: error: unknown register name ‘edi’ in ‘asm’
patternsearch.cpp: In function ‘bool patternsearch::hasAESNIInstructions()’:
patternsearch.cpp:263:21: error: unknown register name ‘edi’ in ‘asm’`

**Comment by FreeTrade** [comment]
I think this code might be orphaned - so probably safe just to remove it remove these two functions -


    // http://blog.paphus.com/blog/2012/07/24/runtime-cpu-feature-checking/
    void cpuid(unsigned info, unsigned *eax, unsigned *ebx, unsigned *ecx, unsigned *edx)
      {
        *eax = info;
        __asm volatile
          ("mov %%ebx, %%edi;" /* 32bit PIC: don't clobber ebx */
           "cpuid;"
           "mov %%ebx, %%esi;"
           "mov %%edi, %%ebx;"
           :"+a" (*eax), "=S" (*ebx), "=c" (*ecx), "=d" (*edx)
           : :"edi");
    }

    bool hasAESNIInstructions(){
        unsigned int eax, ebx, ecx, edx;
        cpuid(1, &eax, &ebx, &ecx, &edx);
        return ((edx & 0x2000000) != 0);
    }

**Comment by Fuzzbawls** [comment]
I'll dig around some more and see if this helps

**Comment by Fuzzbawls** [comment]
Fixed in #44
