### ISSUE TITLE
Deposit table date format

### ISSUE THREAD

**Issue by Vetro7** [HOdlcoin/HOdlcoin#58]
Either we have the OS populate the date format, have the user select the format, or label the format (day/month/year).

**Comment by Fuzzbawls** [comment]
should be a way to use the host OS's date format, which would be the most universal solution and require zero user interaction.

**Comment by FreeTrade** [comment]
This was reversed to year/month/day to better support the alphabetic sort that is easily possible on this table. Also less likely to have the month/day confusion
