### ISSUE TITLE
E-mail notifications?

### ISSUE THREAD

**Issue by scavern** [HOdlcoin/HOdlcoin#59]
Would be fantastic to get email notifications on either maturity or when successfully mined!

**Comment by Fuzzbawls** [comment]
You can use an external script with walletnotify to do pretty much whatever you want when receiving/sending any kind of transaction (including mined blocks).

This however won't help with when a deposit matures.

**Comment by scavern** [comment]
Ah thanks. But when a deposit matures is it seen as being deposited back into the wallet though?

**Comment by Fuzzbawls** [comment]
nope, it is just unlocked and made available as an output, so no on-chain transaction occurs when a deposit matures

**Comment by scavern** [comment]
Great, thanks !
