### ISSUE TITLE
Neet to set the ValidationState object too if there is an error

### ISSUE THREAD

**Issue by bitbandi** [HOdlcoin/HOdlcoin#62]
Some errors in AcceptToMemoryPool didnt set the state object.

(i cant made pullrequest, becuase github dont allow to fork hodhlcoin repo)
here is the commit: https://github.com/bitbandi/HOdlcoin/commit/adb95e9e480e723ebe1be0b2b878570a852b3424 , cherry-pick it!

**Comment by ghobson2013** [comment]
Thanks bitbandi, i submitted the PR on behalf of you.
