### ISSUE TITLE
Transaction List Not Showing HODL transactions sent to others

### ISSUE THREAD

**Issue by FreeTrade** [HOdlcoin/HOdlcoin#63]
If a HODL is sent to an address not in the wallet, it's not showing up on the transaction list.

**Comment by DisasterFaster** [comment]
I deleted the block chains on the sending nodes but I do have a copy of the failed transactions on the receiving node as follows:

Status: conflicted
Date: 6/8/2017 10:13
From: unknown
To: HCtWb7De1PEpRcPZ1UX1K7Vx9DEfSoHHAL (own address, label: From Miners 6-8-2017)
Credit: 44.00077004 HODL
Net amount: +44.00077004 HODL
Transaction ID: 12cc68a1c17589a578615a0faa945ab198442260b507b3c46684846b478898ea-000


Status: conflicted
Date: 6/8/2017 10:12
From: unknown
To: HCtWb7De1PEpRcPZ1UX1K7Vx9DEfSoHHAL (own address, label: From Miners 6-8-2017)
Credit: 5.00000000 HODL
Net amount: +5.00000000 HODL
Transaction ID: f36e30016114a5c87cba3a81f6105d106d6c163dbe37fbde9f9f0cea66238e6c-000

Status: conflicted
Date: 6/8/2017 10:08
From: unknown
To: HCtWb7De1PEpRcPZ1UX1K7Vx9DEfSoHHAL (own address, label: From Miners 6-8-2017)
Credit: 1.00000000 HODL
Net amount: +1.00000000 HODL
Transaction ID: b3906fad40edc498d98b90a592b2dd3bebddbceb021ebcf044201cea571f83d6-000

Status: conflicted
Date: 6/8/2017 09:02
From: unknown
To: HCtWb7De1PEpRcPZ1UX1K7Vx9DEfSoHHAL (own address, label: From Miners 6-8-2017)
Credit: 650.03835272 HODL
Net amount: +650.03835272 HODL
Transaction ID: e1042333a84d1fdb5794d626a0d65296639ea13025516cb12d38d6045cd618d4-000

**Comment by ghobson2013** [comment]
Hodl address has to be manually added to the address book , so this is working as designed.
