### ISSUE TITLE
getblocktemplate RPC call always fails

### ISSUE THREAD

**Issue by Fuzzbawls** [HOdlcoin/HOdlcoin#67]
The getblocktemplate RPC call is in a broken state post-fork as it doesn't know about the new requirements for coinbase transactions needing to be locked in a term deposit.

The block validity check always fails as a result.

**Comment by Fuzzbawls** [comment]
I've informed @ocminer about this and am waiting to hear back from him.

**Comment by Qwertylex** [comment]
Is that why I keep getting 
`ERROR: ConnectBlock(): coinbase transaction does not HOdl for one year, hodlblocks=-1`  on debug.log
and `HTTP request failed: The requested URL returned error: 500 Internal Server Error` on the miner
when I try solomining with https://github.com/Optiminer/hodlminer-wolf/ ?

**Comment by Fuzzbawls** [comment]
None of the stand alone miners support HODL's block template to begin with, so solo mining with them doesn't work (and has never worked) irregardless of this particular issue/patch.

This issue/patch is intended only to provide a valid HODL block template via RPC. It is up to the service/software requesting the template to adhere to the template.

**Comment by Fuzzbawls** [comment]
Got conformation from @optiminer that he is using the patch from #68 with his pool. So, I'm going to merge that in and consider the issue closed.

Some footnotes, however:
- the generated template uses an address from the daemon (or the runtime-supplied user address)
- the coinbase transaction is still mutable, and ANY mutations must adhere to network requirements

What this means:
- stand alone mining programs, in addition to needing compatibility with GBT, will also need to support OP_CHECKLOCKTIMEVERIFY in the coinbase transaction.
- pool software that has been updated to support HODL's GBT will also need to support OP_CHECKLOCKTIMEVERIFY in the coinbase transaction.
