### ISSUE TITLE
Wallet crash when solo mining v3.0.0

### ISSUE THREAD

**Issue by haiqu** [HOdlcoin/HOdlcoin#88]
Hardware: Xeon hex-core (Dell T3500 workstation) with 24GB memory
OS: Windows 7 Pro 64-bit

**Comment by Fuzzbawls** [comment]
From the release notes:

NOTE: Windows systems with certain CPUs have shown issues when using the AVX2
optimizations. As such, option flags have been added to disable running with both
the AES and AVX2 optimizations, and can be used as follows:

- `-optimineraes` - Default is 1 (enabled use of Optiminer AES improvements)
- `-optimineravx2` - Default is 0 (disabled use of Optimer AVX2 improvements)

**Comment by haiqu** [comment]
Irrelevant, I'm not using AVX2 and the Xeon has AES-NI.

The previous version (v2.0.0) also crashed under Linux 14.04 on this CPU. I haven't yet tried the new build.

**Comment by FreeTrade** [comment]
Try setting both flags to 0 to see if that helps

**Comment by haiqu** [comment]
OK, apparently my understanding of the optimineraes switch wasn't adequate. Setting it at 0 doesn't disable everything, just some features. Now have a working miner on Win7 and rebuilding under Linux 14.04 with the new switch there off as well. Should be ok from here.
