### ISSUE TITLE
Sort by deposit block doesn't work correctly.

### ISSUE THREAD

**Issue by haiqu** [HOdlcoin/HOdlcoin#89]
Earliest deposit block I have is 42573. Ascending sort starts at 99368. I believe this sort algo is just looking at the first digit, which is crap.

Workaround: Use sort by Estimated Date.

**Comment by ghobson2013** [comment]
Hi , 
Thanks for testing, unfortunately QTable is pretty limited in terms of sorting types, 
Qt.SortOrder = The items are sorted ascending e.g. starts with 'AAA' ends with 'ZZZ' in Latin-1 locales 
As documented here 
http://doc.qt.io/qt-4.8/qtableview.html#sortByColumn
http://doc.qt.io/qt-4.8/qt.html#SortOrder-enum

i am open to suggestions but couldnt find an easy answer. My goal was actually to at least be able to sort on estimated due date, which does work as you noted.

**Comment by ghobson2013** [comment]
this has been resolved in 3.0.1 , I used right justified format, to get the sorting working on blocknumbers.
