### ISSUE TITLE
No support for openssl-dir in configure script

### ISSUE THREAD

**Issue by grungie** [HOdlcoin/HOdlcoin#95]
There is no easy way of specifying a path such as /usr/local/ssl to compile and link against. This can be done e.g. for the Boost library.

In brief, I'd like to try HOdl with a particular openssl engine which depends on my /usr/local build of openssl 1.1

**Comment by ghobson2013** [comment]
I feel your pain , i once tried it, and it can quickly become a dependency rathole...
wish i could help you.
