### ISSUE TITLE
Slow GUI The application will hang for some time 

### ISSUE THREAD

**Issue by theguru30** [HOdlcoin/HOdlcoin#96]
Wallet with many Hodlings more than 3000 entries on the Overview Page will hang. 

Is it possible to delete unneeded entries from this table in order to increase the speed. I think the entries with "Matured (Warning: this amount " no longer need to be displayed. Or in a restart of the application this cleanup.

Thanks in advance

**Comment by ghobson2013** [comment]
hi theguru30 a fix for the sort performance is already merged in the main branch , we re just waiting on fuzzbawls to build a new wallet for all the platforms. If you know how to build from source its already in the main branch. If you ware on windows, I only know how to manually build the wallet for linux,

https://github.com/HOdlcoin/HOdlcoin/pull/91

**Comment by theguru30** [comment]
Hi ghobson2013, thank you for your Answer, i´ve traid but  I could not compile the program. What I noticed  new Coins from the pool which are no longer locked are in the Hodlings overview. I think if the sort over the parameter can be switched off it speed up but with all those entries with 0 TermDays it becomes very confusing.

Thanks in advance

**Comment by ghobson2013** [comment]
Hi Theguru30 this issue should now be resolved in 3.0.1 .
As for getting rid of "matured" entries in Hodlings table, you simply need to re-hodle or send them to yourself , so that they earn daily interest again for 30 days.
